data_load:
  download_dataset_csv: "gauravkumar2525/top-rated-movies-from-tmdb"
  path_dataset_csv: "top_rated_movies.csv"
featurize:
  features_path: "data/df_clear_homework.csv"
data_split:
  test_size: 0.3
  trainset_path: "data/train_movies.csv"
  testset_path: "data/test_movies.csv"
train:
  cv: 5
  model_type: "tree"
  alpha: [0.0001, 0.001, 0.01, 0.05, 0.1]
  n_estimators: [800]
  model_path: "models/movies.joblib"
  power_path: "models/power.joblib"
test:
  model_path: "models/movies.joblib"
  power_path: "models/power.joblib"
  testset_path: "data/test_movies.csv"
  
